input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    remove_field => ["@version", "agent", "ecs", "input", "host"]
  }
}

output {
  loki {
    url => "http://loki:3100/loki/api/v1/push"
    include_fields => ["log_type", "servicio"]
  }
}
